### ISSUE TITLE
Multiple Url are  feature is not working

### ISSUE THREAD

**Issue by CHANDRASEKHAR613** [dllpl/google-fast-indexing#1]
As mentioned in the documentation, Each URL is added on a new line. but indexing for only one URL.

Example:
When I added 5 URLs in the urls.txt, but indexing  for 5th URL only, remaining  1to 4 URLs are skipped

**Comment by dllpl** [comment]
Thanks, I'm already working on it.

**Comment by dllpl** [comment]
> As mentioned in the documentation, Each URL is added on a new line. but indexing for only one URL.
> 
> Example: When I added 5 URLs in the urls.txt, but indexing for 5th URL only, remaining 1to 4 URLs are skipped

It works. Here is an example of a successful response from Google about adding 5 URLs to the indexing queue. **If you get the same response from your links, then the library has done its job!**

**But Google may indeed not index your pages for some of its internal reasons: See** https://developers.google.com/search/docs/fundamentals/get-on-google#do-you-serve-high-quality-content-to-users

Google may not have liked the quality of pages 1-4, but it liked page 5.

```json
{
    "response-1410898662": {
        "urlNotificationMetadata": {
            "url": "https://grand-service.su/",
            "latestUpdate": {
                "notifyTime": "2024-04-05T12:50:44.043333568Z",
                "type": "URL_UPDATED",
                "url": "https://grand-service.su/"
            }
        }
    },
    "response-1549321495": {
        "urlNotificationMetadata": {
            "url": "https://grand-service.su/remont-televizorov/bang-and-olufsen",
            "latestUpdate": {
                "notifyTime": "2024-04-05T12:50:44.047527414Z",
                "type": "URL_UPDATED",
                "url": "https://grand-service.su/remont-televizorov/bang-and-olufsen"
            }
        }
    },
    "response-1578195267": {
        "urlNotificationMetadata": {
            "url": "https://grand-service.su/remont-duhovyh-shkafov/kitfort",
            "latestUpdate": {
                "notifyTime": "2024-04-05T12:50:44.042969840Z",
                "type": "URL_UPDATED",
                "url": "https://grand-service.su/remont-duhovyh-shkafov/kitfort"
            }
        }
    },
}
```

**Comment by CHANDRASEKHAR613** [comment]
Hello @dllpl,

Upon debugging, I discovered that `$response = $batch->execute();` will only occur for the last URL, as it lies outside the foreach loop. I've submitted a [PR](https://github.com/dllpl/google-fast-indexing/pull/2) addressing this issue. Kindly review and consider the matter.

Thank you.
